### ISSUE TITLE
Specify the extension category

### ISSUE THREAD

**Issue by mmajcica** [microsoft/azure-devops-extension-tasks#145]
One of the extensions I'm building is both pushed to the marketplace as it is pushed directly to some instances of TFS 2018.
As you can imagine I have an issue with the extension category as currently, it is stating "Build and release" meanwhile in order to get it to the marketplace it needs to be changed into "Azure Pipelines" (or vice-versa). Considering that much extension-related information like "Extension name" can be influenced directly from Publish extension task, I was wondering if you would accept a PR that will add the possibility to specify one or more categories, split by a comma, and let the task specify them in the vsix?

If so I'll be keen to implement this as soon as possible.
Obviously, if you have other suggestions on how to solve this issue, I'll be happy to hear about it.

**Comment by jessehouwing** [comment]
Since the Categories and their mappings are fixed, couldn't a version property ion the TFS marketplace connection make this a much cleaner experience
I like the Idea, would accept a pull request under the following acceptance criteria:

 * [ ] works with single-version task extensions
 * [ ] works with multi-version task extensions
 * [ ] additional UI requirements
   * [ ] No UI required (detected by querying version of karketplace as part of workflow?)
   * [ ] Or: Version specified in TFS Marketplace Connection dialog
   * [ ] Or: Version dropdown only shows when picking Azure DevOps Server in target
 * [ ]works on the Publish task
  * [ ] works in publish from vsix
  * [ ] works in publish from manifest

My guess is that only the Publish task would need updating, since the package task has no notion of the target environment.

**Comment by mmajcica** [comment]
That is also possible, but it should not just happen. A check box in UI should state something like, Update Extension Categories or similar.

I also think that only the Publish task would need this and it will be very handy.

**Comment by jessehouwing** [comment]
I think that just using the old names and version 0.6 of TFX will allow you to publish to both.

You can also publish to the marketplace and then download the server VSIX, I believe that will have a patched manifest.... Some things ti investigate ;).

**Comment by jessehouwing** [comment]
As an alternative, you can:

 *  publish from manifest
 * use multiple manifest files
 * put the category in a stand-alone manifest file

The strategy is laid out in this SO answer ed that should work just fine.

https://stackoverflow.com/questions/56029313/how-to-test-new-azure-devops-extension-version-before-publishing-it-for-everyone/56029399#56029399

**Comment by mmajcica** [comment]
I've tried with tfx 0.6.4 and I'm getting:
Failed Request: Internal Server Error(500) - The stated category 'Build and release' is no longer supported.

I would not like to generate multiple artifacts to publish in the same pipeline, it would be cleaner if this transformation is done inside the task itself.
So instead of writing my own script to do this and make mess around, I would be happier to contribute and make the publish task capable of taking care of this.
If you have time we can have a quick chat about it rangers slack?

**Comment by jessehouwing** [comment]
That also allows you to package 2 packages as part op the package stage. That may be a lot cleaner.

**Comment by mmajcica** [comment]
I took a look into the tfx and as far as I can see, there is no command that will tell you more about the endpoint that is used. Then I said, well, let's see if via REST we can't this info. Again, no luck. If you have any idea on how to understand the underlying version of TFS, I can implement a "transparent" switch of the categories.
Otherwise, I'll go with 2 artifacts path.
