### ISSUE TITLE
outputVariable has disappeared, not working

### ISSUE THREAD

**Issue by AdamczykMaciej** [microsoft/azure-devops-extension-tasks#327]
OutputVariable disappeared - it was working in 3.2.123 and v3 but now v3 is using 3.5.x by default and the output variable is not working. Please fix it, we really need it in our pipelines.
![image](https://user-images.githubusercontent.com/34938878/207864578-0fe87ef2-5dea-48f8-ac3d-9f67e8415a6d.png)

**Comment by jessehouwing** [comment]
See: https://stackoverflow.com/questions/73609332/use-an-output-variable-as-a-global-variable-in-azure-yaml-pipeline/73609482#73609482

I've updated the task to *always* register the value as an output variable and we've taken away the ability to specify it.

Instead, just name the task and the variable will always add: `.Extension.Version`.

If that doesn't work for you, consider adding `@3.2.123` to revert back to the version before this change.

**Comment by jdholbrook81** [comment]
One of my pipelines was using the outputVariable parameter and as a result broke. Was able to get my pipeline working again with this information. Thank you.

**Comment by jessehouwing** [comment]
Sorry for breaking you folks.

**Comment by smkell** [comment]
I know that his issue is closed, but I'm curious why the change was also made to the `v3` of the task? Was that breaking change done intentionally? If not could a new version of the task be released that reverts the breaking change to `v3`? 

I'm sure there's a good reason for the change in general, but I'd expect that breaking changes to inputs only happen in major version releases and that users could evaluate changes without needing to implement emergency workarounds.

**Comment by jessehouwing** [comment]
@smkell it happened because of a versioning thing that turned out to be a mistake.

I upped the version to @4 prior to the release of the Node16 handler updates to accommodate this breaking change. But that meant the query version would have had version @5 for Node16, where all other tasks would have had @4. So I backported the latest versions of each task into the extension for backwards compatibility. I had forgotten about the breaking change, breaking you, and I would now break the people who made the fix.

The whole outputVariable parameter has been marked deprecated for a long time and there is an easy workaround by specifying an exact version number or implementing the 'correct' way to reference the variable.

On top it that, everyone needs to move to the new @4 anyway due to the Node16 handler updates.

So I had to make a call and so far only 3 people have had an issue with it. I'm really sorry I broke you, but it feels it was the right call.

**Comment by jessehouwing** [comment]
@smkell managed to find the reason for the bug I was fighting to support both the new and the old handling and found a workaround. Pushing a new version of the task that should unbreak @3.

Thanks for keeping me honest, but please do upgrade to `@4` ;).
